<?php

/**
 * @file
 * Contains headless.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function headless_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {

    // Main module help for the headless module.
    case 'help.page.headless':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Exposes Drupal 8 user operations as routes that support the JSON exchange format.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_headless_data_alter().
 */
/*function headless_headless_data_alter(&$data) {
  $config = \Drupal::config('headless.config');

  //
  // ATTENTION DEVELOPERS
  //
  // The following code should be relocated to a custom module to be
  // invoked as a hook. This, including the related HeadlessConfigForm
  // settings will be *removed* in a future release so you should not
  // rely on it. Add this to your custom module instead.
  //

  if ($data['form_id'] == 'user_login_form') {

    // Get the current user data.
    $storage = \Drupal::entityTypeManager()
      ->getStorage('user');

    $user = $storage->load(\Drupal::currentUser()->id());

    // Prepare new JSON response.
    $data = array();
    foreach ($config->get('user_fields') as $field_name) {
      $data[$field_name] = $user->get($field_name)->value;
    }
  }
}*/
